SELECT SUBSTRING(DATETIME,11,3) as HOUR, COUNT(SUBSTRING(DATETIME,11,3)) as COUNT
FROM ANIMAL_OUTS
WHERE SUBSTRING(DATETIME,11,3) BETWEEN 9 AND 19
GROUP BY SUBSTRING(DATETIME,11,3)
ORDER BY SUBSTRING(DATETIME,11,3)